# SPDX-FileCopyrightText: 2023 Serokell <https://serokell.io/>
#
# SPDX-License-Identifier: MPL-2.0

name: master-update

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@v3

      - name: Create a pre-release
        run: |
          export GITHUB_TOKEN=${{ env.GITHUB_TOKEN }}
          nix shell .#curl .#gitAndTools.hub -c bash -c "curl https://raw.githubusercontent.com/serokell/scratch/release-binary/scripts/release-binary.sh | bash"

      - name: Push latest image to dockerhub
        run: |
          export DOCKERHUB_PASSWORD=${{ env.DOCKERHUB_PASSWORD }}
          nix build -L .#docker-image
          nix shell .#skopeo -c ./scripts/upload-docker-image.sh "docker-archive:$(readlink result)" "docker://docker.io/serokell/xrefcheck:latest"
